// Generated by odin2 (version 0.3.41) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(minimal_discrete)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(inc, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class minimal_discrete {
public:
  minimal_discrete() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 1> state;
      } offset;
    } odin;
    real_type inc;
  };
  struct internal_state {};
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type inc = dust2::r::read_real(parameters, "inc", 1);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, inc};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.inc = dust2::r::read_real(parameters, "inc", shared.inc);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    state_next[0] = S + shared.inc;
  }
};
