// Generated by odin2 (version 0.3.41) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(susceptible_balance_discrete)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(births, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vaccinated, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(cases, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class susceptible_balance_discrete {
public:
  susceptible_balance_discrete() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 1> state;
      } offset;
    } odin;
    real_type rho;
    real_type births;
    real_type vaccinated;
    real_type cases;
  };
  struct internal_state {};
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type rho = dust2::r::read_real(parameters, "rho", 1);
    const real_type births = dust2::r::read_real(parameters, "births", 0);
    const real_type vaccinated = dust2::r::read_real(parameters, "vaccinated", 0);
    const real_type cases = dust2::r::read_real(parameters, "cases", 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, rho, births, vaccinated, cases};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.births = dust2::r::read_real(parameters, "births", shared.births);
    shared.vaccinated = dust2::r::read_real(parameters, "vaccinated", shared.vaccinated);
    shared.cases = dust2::r::read_real(parameters, "cases", shared.cases);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    state_next[0] = monty::math::max<real_type>(0, S + shared.births - shared.vaccinated - shared.cases / shared.rho);
  }
};
