// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_time(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_rng_state(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// minimal_discrete.cpp
SEXP dust2_system_minimal_discrete_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_minimal_discrete_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_minimal_discrete_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_internals(SEXP ptr, SEXP include_coefficients, SEXP include_history) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_internals(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(include_coefficients), cpp11::as_cpp<cpp11::decay_t<bool>>(include_history)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_time(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// sir_basic.cpp
SEXP dust2_system_sir_basic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_sir_basic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sir_basic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_time(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_rng_state(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// sirv_annual.cpp
SEXP dust2_system_sirv_annual_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_sirv_annual_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_sirv_annual_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_time(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_rng_state(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// susceptible_balance.cpp
SEXP dust2_system_susceptible_balance_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_time(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_rng_state(cpp11::sexp ptr);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// susceptible_balance_discrete.cpp
SEXP dust2_system_susceptible_balance_discrete_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _vpdsus_dust2_system_susceptible_balance_discrete_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_susceptible_balance_discrete_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_vpdsus_dust2_system_minimal_discrete_alloc",                         (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_alloc,                         8},
    {"_vpdsus_dust2_system_minimal_discrete_reorder",                       (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_reorder,                       2},
    {"_vpdsus_dust2_system_minimal_discrete_rng_state",                     (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_rng_state,                     1},
    {"_vpdsus_dust2_system_minimal_discrete_run_to_time",                   (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_run_to_time,                   2},
    {"_vpdsus_dust2_system_minimal_discrete_set_rng_state",                 (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_set_rng_state,                 2},
    {"_vpdsus_dust2_system_minimal_discrete_set_state",                     (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_set_state,                     2},
    {"_vpdsus_dust2_system_minimal_discrete_set_state_initial",             (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_set_state_initial,             1},
    {"_vpdsus_dust2_system_minimal_discrete_set_time",                      (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_set_time,                      2},
    {"_vpdsus_dust2_system_minimal_discrete_simulate",                      (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_simulate,                      5},
    {"_vpdsus_dust2_system_minimal_discrete_state",                         (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_state,                         6},
    {"_vpdsus_dust2_system_minimal_discrete_time",                          (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_time,                          1},
    {"_vpdsus_dust2_system_minimal_discrete_update_pars",                   (DL_FUNC) &_vpdsus_dust2_system_minimal_discrete_update_pars,                   2},
    {"_vpdsus_dust2_system_sir_basic_alloc",                                (DL_FUNC) &_vpdsus_dust2_system_sir_basic_alloc,                                8},
    {"_vpdsus_dust2_system_sir_basic_internals",                            (DL_FUNC) &_vpdsus_dust2_system_sir_basic_internals,                            3},
    {"_vpdsus_dust2_system_sir_basic_reorder",                              (DL_FUNC) &_vpdsus_dust2_system_sir_basic_reorder,                              2},
    {"_vpdsus_dust2_system_sir_basic_rng_state",                            (DL_FUNC) &_vpdsus_dust2_system_sir_basic_rng_state,                            1},
    {"_vpdsus_dust2_system_sir_basic_run_to_time",                          (DL_FUNC) &_vpdsus_dust2_system_sir_basic_run_to_time,                          2},
    {"_vpdsus_dust2_system_sir_basic_set_rng_state",                        (DL_FUNC) &_vpdsus_dust2_system_sir_basic_set_rng_state,                        2},
    {"_vpdsus_dust2_system_sir_basic_set_state",                            (DL_FUNC) &_vpdsus_dust2_system_sir_basic_set_state,                            2},
    {"_vpdsus_dust2_system_sir_basic_set_state_initial",                    (DL_FUNC) &_vpdsus_dust2_system_sir_basic_set_state_initial,                    1},
    {"_vpdsus_dust2_system_sir_basic_set_time",                             (DL_FUNC) &_vpdsus_dust2_system_sir_basic_set_time,                             2},
    {"_vpdsus_dust2_system_sir_basic_simulate",                             (DL_FUNC) &_vpdsus_dust2_system_sir_basic_simulate,                             5},
    {"_vpdsus_dust2_system_sir_basic_state",                                (DL_FUNC) &_vpdsus_dust2_system_sir_basic_state,                                6},
    {"_vpdsus_dust2_system_sir_basic_time",                                 (DL_FUNC) &_vpdsus_dust2_system_sir_basic_time,                                 1},
    {"_vpdsus_dust2_system_sir_basic_update_pars",                          (DL_FUNC) &_vpdsus_dust2_system_sir_basic_update_pars,                          2},
    {"_vpdsus_dust2_system_sirv_annual_alloc",                              (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_alloc,                              8},
    {"_vpdsus_dust2_system_sirv_annual_reorder",                            (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_reorder,                            2},
    {"_vpdsus_dust2_system_sirv_annual_rng_state",                          (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_rng_state,                          1},
    {"_vpdsus_dust2_system_sirv_annual_run_to_time",                        (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_run_to_time,                        2},
    {"_vpdsus_dust2_system_sirv_annual_set_rng_state",                      (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_set_rng_state,                      2},
    {"_vpdsus_dust2_system_sirv_annual_set_state",                          (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_set_state,                          2},
    {"_vpdsus_dust2_system_sirv_annual_set_state_initial",                  (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_set_state_initial,                  1},
    {"_vpdsus_dust2_system_sirv_annual_set_time",                           (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_set_time,                           2},
    {"_vpdsus_dust2_system_sirv_annual_simulate",                           (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_simulate,                           5},
    {"_vpdsus_dust2_system_sirv_annual_state",                              (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_state,                              6},
    {"_vpdsus_dust2_system_sirv_annual_time",                               (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_time,                               1},
    {"_vpdsus_dust2_system_sirv_annual_update_pars",                        (DL_FUNC) &_vpdsus_dust2_system_sirv_annual_update_pars,                        2},
    {"_vpdsus_dust2_system_susceptible_balance_alloc",                      (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_alloc,                      8},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_alloc",             (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_alloc,             8},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_reorder",           (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_reorder,           2},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_rng_state",         (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_rng_state,         1},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_run_to_time",       (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_run_to_time,       2},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_set_rng_state",     (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_set_rng_state,     2},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_set_state",         (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_set_state,         2},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_set_state_initial", (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_set_state_initial, 1},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_set_time",          (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_set_time,          2},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_simulate",          (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_simulate,          5},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_state",             (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_state,             6},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_time",              (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_time,              1},
    {"_vpdsus_dust2_system_susceptible_balance_discrete_update_pars",       (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_discrete_update_pars,       2},
    {"_vpdsus_dust2_system_susceptible_balance_reorder",                    (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_reorder,                    2},
    {"_vpdsus_dust2_system_susceptible_balance_rng_state",                  (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_rng_state,                  1},
    {"_vpdsus_dust2_system_susceptible_balance_run_to_time",                (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_run_to_time,                2},
    {"_vpdsus_dust2_system_susceptible_balance_set_rng_state",              (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_set_rng_state,              2},
    {"_vpdsus_dust2_system_susceptible_balance_set_state",                  (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_set_state,                  2},
    {"_vpdsus_dust2_system_susceptible_balance_set_state_initial",          (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_set_state_initial,          1},
    {"_vpdsus_dust2_system_susceptible_balance_set_time",                   (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_set_time,                   2},
    {"_vpdsus_dust2_system_susceptible_balance_simulate",                   (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_simulate,                   5},
    {"_vpdsus_dust2_system_susceptible_balance_state",                      (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_state,                      6},
    {"_vpdsus_dust2_system_susceptible_balance_time",                       (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_time,                       1},
    {"_vpdsus_dust2_system_susceptible_balance_update_pars",                (DL_FUNC) &_vpdsus_dust2_system_susceptible_balance_update_pars,                2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_vpdsus(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
