// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.41) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(sirv_annual)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(beta, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(gamma, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(mu, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(births, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vaccinated, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(n_pop, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(S0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(R0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(V0, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class sirv_annual {
public:
  sirv_annual() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 7> state;
      } offset;
    } odin;
    real_type beta;
    real_type gamma;
    real_type mu;
    real_type rho;
    real_type births;
    real_type vaccinated;
    real_type n_pop;
    real_type S0;
    real_type I0;
    real_type R0;
    real_type V0;
  };
  struct internal_state {};
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type beta = dust2::r::read_real(parameters, "beta", static_cast<real_type>(0.5));
    const real_type gamma = dust2::r::read_real(parameters, "gamma", static_cast<real_type>(0.20000000000000001));
    const real_type mu = dust2::r::read_real(parameters, "mu", static_cast<real_type>(0.01));
    const real_type rho = dust2::r::read_real(parameters, "rho", static_cast<real_type>(0.20000000000000001));
    const real_type births = dust2::r::read_real(parameters, "births", 0);
    const real_type vaccinated = dust2::r::read_real(parameters, "vaccinated", 0);
    const real_type n_pop = dust2::r::read_real(parameters, "n_pop", 1);
    const real_type S0 = dust2::r::read_real(parameters, "S0", 0);
    const real_type I0 = dust2::r::read_real(parameters, "I0", 0);
    const real_type R0 = dust2::r::read_real(parameters, "R0", 0);
    const real_type V0 = dust2::r::read_real(parameters, "V0", 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"I", {}},
      {"R", {}},
      {"V", {}},
      {"reported_cases", {}},
      {"susceptible_n", {}},
      {"susceptible_prop", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, beta, gamma, mu, rho, births, vaccinated, n_pop, S0, I0, R0, V0};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.beta = dust2::r::read_real(parameters, "beta", shared.beta);
    shared.gamma = dust2::r::read_real(parameters, "gamma", shared.gamma);
    shared.mu = dust2::r::read_real(parameters, "mu", shared.mu);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.births = dust2::r::read_real(parameters, "births", shared.births);
    shared.vaccinated = dust2::r::read_real(parameters, "vaccinated", shared.vaccinated);
    shared.n_pop = dust2::r::read_real(parameters, "n_pop", shared.n_pop);
    shared.S0 = dust2::r::read_real(parameters, "S0", shared.S0);
    shared.I0 = dust2::r::read_real(parameters, "I0", shared.I0);
    shared.R0 = dust2::r::read_real(parameters, "R0", shared.R0);
    shared.V0 = dust2::r::read_real(parameters, "V0", shared.V0);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.S0;
    state[1] = shared.I0;
    state[2] = shared.R0;
    state[3] = shared.V0;
    state[4] = 0;
    state[5] = shared.S0;
    state[6] = (shared.n_pop > 0 ? shared.S0 / shared.n_pop : 0);
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto I = state[1];
    const auto R = state[2];
    const auto V = state[3];
    const real_type inf = shared.beta * S * I / shared.n_pop;
    const real_type rec = shared.gamma * I;
    const real_type death_S = shared.mu * S;
    const real_type death_I = shared.mu * I;
    const real_type death_R = shared.mu * R;
    const real_type death_V = shared.mu * V;
    state_next[0] = monty::math::max<real_type>(0, S + shared.births - shared.vaccinated - inf - death_S);
    state_next[1] = monty::math::max<real_type>(0, I + inf - rec - death_I);
    state_next[2] = monty::math::max<real_type>(0, R + rec - death_R);
    state_next[3] = monty::math::max<real_type>(0, V + shared.vaccinated - death_V);
    state_next[4] = shared.rho * inf;
    state_next[5] = S;
    state_next[6] = (shared.n_pop > 0 ? S / shared.n_pop : 0);
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>

[[cpp11::register]]
SEXP dust2_system_sirv_annual_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<sirv_annual>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_sirv_annual_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<sirv_annual>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<sirv_annual>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<sirv_annual>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<sirv_annual>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<sirv_annual>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<sirv_annual>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<sirv_annual>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<sirv_annual>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<sirv_annual>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<sirv_annual>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_sirv_annual_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<sirv_annual>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}
