// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.41) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(susceptible_balance_discrete)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(births, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(vaccinated, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(cases, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
class susceptible_balance_discrete {
public:
  susceptible_balance_discrete() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 1> state;
      } offset;
    } odin;
    real_type rho;
    real_type births;
    real_type vaccinated;
    real_type cases;
  };
  struct internal_state {};
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    const real_type rho = dust2::r::read_real(parameters, "rho", 1);
    const real_type births = dust2::r::read_real(parameters, "births", 0);
    const real_type vaccinated = dust2::r::read_real(parameters, "vaccinated", 0);
    const real_type cases = dust2::r::read_real(parameters, "cases", 0);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, rho, births, vaccinated, cases};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.births = dust2::r::read_real(parameters, "births", shared.births);
    shared.vaccinated = dust2::r::read_real(parameters, "vaccinated", shared.vaccinated);
    shared.cases = dust2::r::read_real(parameters, "cases", shared.cases);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    state_next[0] = monty::math::max<real_type>(0, S + shared.births - shared.vaccinated - shared.cases / shared.rho);
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<susceptible_balance_discrete>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<susceptible_balance_discrete>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<susceptible_balance_discrete>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<susceptible_balance_discrete>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_susceptible_balance_discrete_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<susceptible_balance_discrete>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}
