# Generated by cpp11: do not edit by hand

dust2_system_minimal_discrete_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_minimal_discrete_run_to_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_run_to_time`, ptr, r_time)
}

dust2_system_minimal_discrete_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_minimal_discrete_time <- function(ptr) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_time`, ptr)
}

dust2_system_minimal_discrete_set_state_initial <- function(ptr) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_set_state_initial`, ptr)
}

dust2_system_minimal_discrete_set_state <- function(ptr, r_state) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_set_state`, ptr, r_state)
}

dust2_system_minimal_discrete_reorder <- function(ptr, r_index) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_reorder`, ptr, r_index)
}

dust2_system_minimal_discrete_rng_state <- function(ptr) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_rng_state`, ptr)
}

dust2_system_minimal_discrete_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_set_rng_state`, ptr, r_rng_state)
}

dust2_system_minimal_discrete_set_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_set_time`, ptr, r_time)
}

dust2_system_minimal_discrete_update_pars <- function(ptr, pars) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_update_pars`, ptr, pars)
}

dust2_system_minimal_discrete_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_minimal_discrete_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_basic_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_vpdsus_dust2_system_sir_basic_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sir_basic_internals <- function(ptr, include_coefficients, include_history) {
  .Call(`_vpdsus_dust2_system_sir_basic_internals`, ptr, include_coefficients, include_history)
}

dust2_system_sir_basic_run_to_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_sir_basic_run_to_time`, ptr, r_time)
}

dust2_system_sir_basic_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_sir_basic_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sir_basic_time <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sir_basic_time`, ptr)
}

dust2_system_sir_basic_set_state_initial <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sir_basic_set_state_initial`, ptr)
}

dust2_system_sir_basic_set_state <- function(ptr, r_state) {
  .Call(`_vpdsus_dust2_system_sir_basic_set_state`, ptr, r_state)
}

dust2_system_sir_basic_reorder <- function(ptr, r_index) {
  .Call(`_vpdsus_dust2_system_sir_basic_reorder`, ptr, r_index)
}

dust2_system_sir_basic_rng_state <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sir_basic_rng_state`, ptr)
}

dust2_system_sir_basic_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_vpdsus_dust2_system_sir_basic_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sir_basic_set_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_sir_basic_set_time`, ptr, r_time)
}

dust2_system_sir_basic_update_pars <- function(ptr, pars) {
  .Call(`_vpdsus_dust2_system_sir_basic_update_pars`, ptr, pars)
}

dust2_system_sir_basic_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_sir_basic_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirv_annual_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_vpdsus_dust2_system_sirv_annual_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_sirv_annual_run_to_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_sirv_annual_run_to_time`, ptr, r_time)
}

dust2_system_sirv_annual_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_sirv_annual_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_sirv_annual_time <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sirv_annual_time`, ptr)
}

dust2_system_sirv_annual_set_state_initial <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sirv_annual_set_state_initial`, ptr)
}

dust2_system_sirv_annual_set_state <- function(ptr, r_state) {
  .Call(`_vpdsus_dust2_system_sirv_annual_set_state`, ptr, r_state)
}

dust2_system_sirv_annual_reorder <- function(ptr, r_index) {
  .Call(`_vpdsus_dust2_system_sirv_annual_reorder`, ptr, r_index)
}

dust2_system_sirv_annual_rng_state <- function(ptr) {
  .Call(`_vpdsus_dust2_system_sirv_annual_rng_state`, ptr)
}

dust2_system_sirv_annual_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_vpdsus_dust2_system_sirv_annual_set_rng_state`, ptr, r_rng_state)
}

dust2_system_sirv_annual_set_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_sirv_annual_set_time`, ptr, r_time)
}

dust2_system_sirv_annual_update_pars <- function(ptr, pars) {
  .Call(`_vpdsus_dust2_system_sirv_annual_update_pars`, ptr, pars)
}

dust2_system_sirv_annual_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_sirv_annual_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_susceptible_balance_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_susceptible_balance_run_to_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_run_to_time`, ptr, r_time)
}

dust2_system_susceptible_balance_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_susceptible_balance_time <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_time`, ptr)
}

dust2_system_susceptible_balance_set_state_initial <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_set_state_initial`, ptr)
}

dust2_system_susceptible_balance_set_state <- function(ptr, r_state) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_set_state`, ptr, r_state)
}

dust2_system_susceptible_balance_reorder <- function(ptr, r_index) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_reorder`, ptr, r_index)
}

dust2_system_susceptible_balance_rng_state <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_rng_state`, ptr)
}

dust2_system_susceptible_balance_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_set_rng_state`, ptr, r_rng_state)
}

dust2_system_susceptible_balance_set_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_set_time`, ptr, r_time)
}

dust2_system_susceptible_balance_update_pars <- function(ptr, pars) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_update_pars`, ptr, pars)
}

dust2_system_susceptible_balance_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_susceptible_balance_discrete_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_susceptible_balance_discrete_run_to_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_run_to_time`, ptr, r_time)
}

dust2_system_susceptible_balance_discrete_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_susceptible_balance_discrete_time <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_time`, ptr)
}

dust2_system_susceptible_balance_discrete_set_state_initial <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_set_state_initial`, ptr)
}

dust2_system_susceptible_balance_discrete_set_state <- function(ptr, r_state) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_set_state`, ptr, r_state)
}

dust2_system_susceptible_balance_discrete_reorder <- function(ptr, r_index) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_reorder`, ptr, r_index)
}

dust2_system_susceptible_balance_discrete_rng_state <- function(ptr) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_rng_state`, ptr)
}

dust2_system_susceptible_balance_discrete_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_set_rng_state`, ptr, r_rng_state)
}

dust2_system_susceptible_balance_discrete_set_time <- function(ptr, r_time) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_set_time`, ptr, r_time)
}

dust2_system_susceptible_balance_discrete_update_pars <- function(ptr, pars) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_update_pars`, ptr, pars)
}

dust2_system_susceptible_balance_discrete_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_vpdsus_dust2_system_susceptible_balance_discrete_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
