## Generated by dust2 (version 0.3.28) - do not edit
minimal_discrete <- structure(
  function() get("minimal_discrete"),
  class = "dust_system_generator",
  name = "minimal_discrete",
  package = "vpdsus",
  path = NULL,
  parameters = data.frame(
    name = "inc",
    type = "real_type",
    constant = FALSE,
    required = FALSE,
    rank = 0L),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
sir_basic <- structure(
  function() get("sir_basic"),
  class = "dust_system_generator",
  name = "sir_basic",
  package = "vpdsus",
  path = NULL,
  parameters = data.frame(
    name = c("beta", "gamma", "v", "births", "n_pop", "S0", "I0", "R0"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
sirv_annual <- structure(
  function() get("sirv_annual"),
  class = "dust_system_generator",
  name = "sirv_annual",
  package = "vpdsus",
  path = NULL,
  parameters = data.frame(
    name = c("beta", "gamma", "mu", "rho", "births", "vaccinated", "n_pop", "S0", "I0", "R0", "V0"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
susceptible_balance_discrete <- structure(
  function() get("susceptible_balance_discrete"),
  class = "dust_system_generator",
  name = "susceptible_balance_discrete",
  package = "vpdsus",
  path = NULL,
  parameters = data.frame(
    name = c("rho", "births", "vaccinated", "cases"),
    type = c("real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
susceptible_balance <- structure(
  function() get("susceptible_balance"),
  class = "dust_system_generator",
  name = "susceptible_balance",
  package = "vpdsus",
  path = NULL,
  parameters = data.frame(
    name = c("rho", "births", "vaccinated", "cases", "S0"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
